name: Build and Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install -legacy-peer-deps
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: gh-pages
